# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa4a45d9da8fbcfb718ab6b5ee682303aae19a453e1f3758c1f1972493ac79a9409dc11e782710c6bb9b4bf9f784dabc7bd506993a73b512292d37c0d450030a

test:
  secret_key_base: 48a58f365f3c3c398a3c246e7ce85028b4381437b9a5fea8ddac8916e87d0354449fb1ba268c045b24ab2ab0d1d1c1ea39f990197a7f2b5a7c109c5a8a57a094

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
